apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  creationTimestamp: null
  name: kfapp
  namespace: <namespace>
spec:
  appdir: ~/kfapp
  components:
  - argo
  - pipeline
  packages:
  - argo
  - common
  - examples
  - pipeline
  repo: ~/kfapp/.cache/master/kubeflow
  useBasicAuth: false
  useIstio: false
  version: master
status: {}
