apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  creationTimestamp: null
  name: kfapp
  namespace: kubeflow
spec:
  appdir: /home/iguazio/kfapp
  components:
  - argo
  - pipeline
  packages:
  - argo
  - common
  - examples
  - pipeline
  repo: /home/iguazio/kfapp/.cache/master/kubeflow
  useBasicAuth: false
  useIstio: false
  version: master
status: {}
